const dummyData = [
      {
        "dID": "401",
        "dDocName": "DEV_000401",
        "dDocAuthor": null,
        "dRevLabel": "1",
        "dDocType": null,
        "dSecurityGroup": null,
        "dDocAccount": null,
        "dDocTitle": null,
        "dCheckedOutUser": null,
        "dInDate": null,
        "folderPath": null,
        "parentGUID": null,
        "primaryFile": null,
        "dOriginalName": null,
        "filecontent": null,
        "customMetadataMap": {
          "dDocOwner": "weblogic",
          "xIPMSYS_BATCH_ID1": "0",
          "xComments": "",
          "dRendition1": "",
          "xPackagedConversions": "",
          "dRendition2": "",
          "dFullTextFormat": "",
          "dDocClass": "",
          "VaultFileSize": "8153",
          "WebFileSize": "8153",
          "xDiscussionCount": "0",
          "dDocTitle": "Test image content 3",
          "dWebExtension": "jpg",
          "otsFormat": "",
          "srfDocSnippet": "",
          "dExtension": "jpg",
          "xStorageRule": "DispByContentId",
          "dDocType": "FSE_DOCUMENTS",
          "dDocFunction": "",
          "xVideoRenditions": "",
          "dDocCreatedDate": "2025-04-14 09:03:57Z",
          "dOutDate": "",
          "dRevClassID": "401",
          "dDocName": "DEV_000401",
          "AlternateFormat": "",
          "xIdcProfile": "",
          "SCORE": "41",
          "dDocAuthor": "weblogic",
          "dDocCreator": "weblogic",
          "dDocLastModifier": "weblogic",
          "xIPMSYS_BATCH_SEQ": "",
          "dPublishType": "",
          "URL": "/cs/groups/internet/documents/fse_documents/zxzf/mdaw/~edisp/dev_000401.jpg",
          "dFormat": "image/jpeg",
          "dInDate": "2025-04-14 09:03:00Z",
          "xDiscussionType": "N/A",
          "xIPMSYS_APP_ID": "",
          "xPartitionId": "",
          "xWebFlag": "",
          "dOriginalName": "Rohit Photo.jpg",
          "dSecurityGroup": "Internet",
          "dGif": "adacct.gif",
          "dCreateDate": "2025-04-14 09:03:57Z",
          "dRevisionID": "1",
          "dDocLastModifiedDate": "2025-04-14 09:03:57Z",
          "otsCharset": "",
          "dRevLabel": "1",
          "xDamConversionType": "",
          "dDocAccount": "",
          "otsLanguage": "",
          "xLibraryGUID": "",
          "dID": "401"
        }
      },
      {
        "dID": "210",
        "dDocName": "DEV_000207",
        "dDocAuthor": null,
        "dRevLabel": "1",
        "dDocType": null,
        "dSecurityGroup": null,
        "dDocAccount": null,
        "dDocTitle": null,
        "dCheckedOutUser": null,
        "dInDate": null,
        "folderPath": null,
        "parentGUID": null,
        "primaryFile": null,
        "dOriginalName": null,
        "filecontent": null,
        "customMetadataMap": {
          "dDocOwner": "weblogic",
          "xIPMSYS_BATCH_ID1": "0",
          "xComments": "",
          "dRendition1": "",
          "xPackagedConversions": "",
          "dRendition2": "",
          "dFullTextFormat": "",
          "dDocClass": "",
          "VaultFileSize": "208933",
          "WebFileSize": "208933",
          "xDiscussionCount": "0",
          "dDocTitle": "Test image content 2",
          "dWebExtension": "png",
          "otsFormat": "",
          "srfDocSnippet": "",
          "dExtension": "png",
          "xStorageRule": "DispByContentId",
          "dDocType": "FSE_DOCUMENTS",
          "dDocFunction": "",
          "xVideoRenditions": "",
          "dDocCreatedDate": "2025-03-24 10:36:47Z",
          "dOutDate": "",
          "dRevClassID": "207",
          "dDocName": "DEV_000207",
          "AlternateFormat": "",
          "xIdcProfile": "",
          "SCORE": "41",
          "dDocAuthor": "weblogic",
          "dDocCreator": "weblogic",
          "dDocLastModifier": "weblogic",
          "xIPMSYS_BATCH_SEQ": "",
          "dPublishType": "",
          "URL": "/cs/groups/internet/documents/fse_documents/zxzf/mdaw/~edisp/dev_000207.png",
          "dFormat": "image/png",
          "dInDate": "2025-03-24 10:36:00Z",
          "xDiscussionType": "N/A",
          "xIPMSYS_APP_ID": "",
          "xPartitionId": "",
          "xWebFlag": "",
          "dOriginalName": "2021-03-25 (4).png",
          "dSecurityGroup": "Internet",
          "dGif": "adacct.gif",
          "dCreateDate": "2025-03-24 10:36:47Z",
          "dRevisionID": "1",
          "dDocLastModifiedDate": "2025-03-24 10:36:47Z",
          "otsCharset": "",
          "dRevLabel": "1",
          "xDamConversionType": "",
          "dDocAccount": "",
          "otsLanguage": "",
          "xLibraryGUID": "",
          "dID": "210"
        }
      },
      {
        "dID": "207",
        "dDocName": "DEV_000206",
        "dDocAuthor": null,
        "dRevLabel": "1",
        "dDocType": null,
        "dSecurityGroup": null,
        "dDocAccount": null,
        "dDocTitle": null,
        "dCheckedOutUser": null,
        "dInDate": null,
        "folderPath": null,
        "parentGUID": null,
        "primaryFile": null,
        "dOriginalName": null,
        "filecontent": null,
        "customMetadataMap": {
          "dDocOwner": "weblogic",
          "xIPMSYS_BATCH_ID1": "0",
          "xComments": "",
          "dRendition1": "",
          "xPackagedConversions": "",
          "dRendition2": "",
          "dFullTextFormat": "",
          "dDocClass": "",
          "VaultFileSize": "440947",
          "WebFileSize": "440947",
          "xDiscussionCount": "0",
          "dDocTitle": "Test image content",
          "dWebExtension": "png",
          "otsFormat": "",
          "srfDocSnippet": "",
          "dExtension": "png",
          "xStorageRule": "DispByContentId",
          "dDocType": "FSE_DOCUMENTS",
          "dDocFunction": "",
          "xVideoRenditions": "",
          "dDocCreatedDate": "2025-03-24 07:43:19Z",
          "dOutDate": "",
          "dRevClassID": "206",
          "dDocName": "DEV_000206",
          "AlternateFormat": "",
          "xIdcProfile": "",
          "SCORE": "41",
          "dDocAuthor": "weblogic",
          "dDocCreator": "weblogic",
          "dDocLastModifier": "weblogic",
          "xIPMSYS_BATCH_SEQ": "",
          "dPublishType": "",
          "URL": "/cs/groups/internet/documents/fse_documents/zxzf/mdaw/~edisp/dev_000206.png",
          "dFormat": "image/png",
          "dInDate": "2025-03-24 07:42:00Z",
          "xDiscussionType": "N/A",
          "xIPMSYS_APP_ID": "",
          "xPartitionId": "",
          "xWebFlag": "",
          "dOriginalName": "2021-03-09 (1).png",
          "dSecurityGroup": "Internet",
          "dGif": "adacct.gif",
          "dCreateDate": "2025-03-24 07:43:19Z",
          "dRevisionID": "1",
          "dDocLastModifiedDate": "2025-03-24 07:43:19Z",
          "otsCharset": "",
          "dRevLabel": "1",
          "xDamConversionType": "",
          "dDocAccount": "",
          "otsLanguage": "",
          "xLibraryGUID": "",
          "dID": "207"
        }
      },
      {
        "dID": "3",
        "dDocName": "DEV_000003",
        "dDocAuthor": null,
        "dRevLabel": "1",
        "dDocType": null,
        "dSecurityGroup": null,
        "dDocAccount": null,
        "dDocTitle": null,
        "dCheckedOutUser": null,
        "dInDate": null,
        "folderPath": null,
        "parentGUID": null,
        "primaryFile": null,
        "dOriginalName": null,
        "filecontent": null,
        "customMetadataMap": {
          "dDocOwner": "weblogic",
          "xIPMSYS_BATCH_ID1": "0",
          "xComments": "",
          "dRendition1": "",
          "xPackagedConversions": "",
          "dRendition2": "",
          "dFullTextFormat": "",
          "dDocClass": "",
          "VaultFileSize": "4640",
          "WebFileSize": "4640",
          "xDiscussionCount": "0",
          "dDocTitle": "Test Folio checkin",
          "dWebExtension": "hda",
          "otsFormat": "",
          "srfDocSnippet": "",
          "dExtension": "hda",
          "xStorageRule": "DispByContentId",
          "dDocType": "Document",
          "dDocFunction": "",
          "xVideoRenditions": "",
          "dDocCreatedDate": "2025-03-07 18:16:15Z",
          "dOutDate": "",
          "dRevClassID": "3",
          "dDocName": "DEV_000003",
          "AlternateFormat": "",
          "xIdcProfile": "",
          "SCORE": "41",
          "dDocAuthor": "weblogic",
          "dDocCreator": "weblogic",
          "dDocLastModifier": "weblogic",
          "xIPMSYS_BATCH_SEQ": "",
          "dPublishType": "",
          "URL": "/cs/groups/public/documents/document/zxzf/mdaw/~edisp/dev_000003.hda",
          "dFormat": "Application/hda",
          "dInDate": "2025-03-07 18:15:00Z",
          "xDiscussionType": "N/A",
          "xIPMSYS_APP_ID": "",
          "xPartitionId": "",
          "xWebFlag": "",
          "dOriginalName": "task.hda",
          "dSecurityGroup": "Public",
          "dGif": "ucm_document.png",
          "dCreateDate": "2025-03-07 18:16:15Z",
          "dRevisionID": "1",
          "dDocLastModifiedDate": "2025-03-07 18:16:15Z",
          "otsCharset": "",
          "dRevLabel": "1",
          "xDamConversionType": "",
          "dDocAccount": "",
          "otsLanguage": "",
          "xLibraryGUID": "",
          "dID": "3"
        }
      },
      {
        "dID": "2",
        "dDocName": "DEV_000002",
        "dDocAuthor": null,
        "dRevLabel": "1",
        "dDocType": null,
        "dSecurityGroup": null,
        "dDocAccount": null,
        "dDocTitle": null,
        "dCheckedOutUser": null,
        "dInDate": null,
        "folderPath": null,
        "parentGUID": null,
        "primaryFile": null,
        "dOriginalName": null,
        "filecontent": null,
        "customMetadataMap": {
          "dDocOwner": "weblogic",
          "xIPMSYS_BATCH_ID1": "0",
          "xComments": "",
          "dRendition1": "",
          "xPackagedConversions": "",
          "dRendition2": "",
          "dFullTextFormat": "",
          "dDocClass": "",
          "VaultFileSize": "1501",
          "WebFileSize": "1501",
          "xDiscussionCount": "0",
          "dDocTitle": "Test Folio Template",
          "dWebExtension": "xcst",
          "otsFormat": "",
          "srfDocSnippet": "",
          "dExtension": "xcst",
          "xStorageRule": "DispByContentId",
          "dDocType": "Document",
          "dDocFunction": "",
          "xVideoRenditions": "",
          "dDocCreatedDate": "2025-03-07 16:50:38Z",
          "dOutDate": "",
          "dRevClassID": "2",
          "dDocName": "DEV_000002",
          "AlternateFormat": "",
          "xIdcProfile": "",
          "SCORE": "41",
          "dDocAuthor": "weblogic",
          "dDocCreator": "weblogic",
          "dDocLastModifier": "weblogic",
          "xIPMSYS_BATCH_SEQ": "",
          "dPublishType": "",
          "URL": "/cs/groups/public/documents/document/zxzf/mdaw/~edisp/dev_000002.xcst",
          "dFormat": "text/xcst",
          "dInDate": "2025-03-07 16:50:00Z",
          "xDiscussionType": "N/A",
          "xIPMSYS_APP_ID": "",
          "xPartitionId": "",
          "xWebFlag": "",
          "dOriginalName": "dev_000002.xcst",
          "dSecurityGroup": "Public",
          "dGif": "ucm_document.png",
          "dCreateDate": "2025-03-07 16:50:38Z",
          "dRevisionID": "1",
          "dDocLastModifiedDate": "2025-03-07 16:50:38Z",
          "otsCharset": "",
          "dRevLabel": "1",
          "xDamConversionType": "",
          "dDocAccount": "",
          "otsLanguage": "",
          "xLibraryGUID": "",
          "dID": "2"
        }
      },
      {
        "dID": "1",
        "dDocName": "DEV_000001",
        "dDocAuthor": null,
        "dRevLabel": "1",
        "dDocType": null,
        "dSecurityGroup": null,
        "dDocAccount": null,
        "dDocTitle": null,
        "dCheckedOutUser": null,
        "dInDate": null,
        "folderPath": null,
        "parentGUID": null,
        "primaryFile": null,
        "dOriginalName": null,
        "filecontent": null,
        "customMetadataMap": {
          "dDocOwner": "weblogic",
          "xIPMSYS_BATCH_ID1": "0",
          "xComments": "",
          "dRendition1": "",
          "xPackagedConversions": "",
          "dRendition2": "",
          "dFullTextFormat": "",
          "dDocClass": "",
          "VaultFileSize": "4640",
          "WebFileSize": "4640",
          "xDiscussionCount": "0",
          "dDocTitle": "test",
          "dWebExtension": "hda",
          "otsFormat": "",
          "srfDocSnippet": "",
          "dExtension": "hda",
          "xStorageRule": "DispByContentId",
          "dDocType": "Document",
          "dDocFunction": "",
          "xVideoRenditions": "",
          "dDocCreatedDate": "2025-03-07 16:27:13Z",
          "dOutDate": "",
          "dRevClassID": "1",
          "dDocName": "DEV_000001",
          "AlternateFormat": "",
          "xIdcProfile": "",
          "SCORE": "41",
          "dDocAuthor": "weblogic",
          "dDocCreator": "weblogic",
          "dDocLastModifier": "weblogic",
          "xIPMSYS_BATCH_SEQ": "",
          "dPublishType": "",
          "URL": "/cs/groups/public/documents/document/zxzf/mdaw/~edisp/dev_000001.hda",
          "dFormat": "Application/hda",
          "dInDate": "2025-03-07 16:26:00Z",
          "xDiscussionType": "N/A",
          "xIPMSYS_APP_ID": "",
          "xPartitionId": "",
          "xWebFlag": "",
          "dOriginalName": "task.hda",
          "dSecurityGroup": "Public",
          "dGif": "ucm_document.png",
          "dCreateDate": "2025-03-07 16:27:13Z",
          "dRevisionID": "1",
          "dDocLastModifiedDate": "2025-03-07 16:27:13Z",
          "otsCharset": "",
          "dRevLabel": "1",
          "xDamConversionType": "",
          "dDocAccount": "",
          "otsLanguage": "",
          "xLibraryGUID": "",
          "dID": "1"
        }
      }
    ]
export default dummyData;